core.fleet_add = {
    makes: [
        'Любая марка',
        'AC',
        'Acura',
        'Alfa Romeo',
        'Aro',
        'Asia',
        'Aston Martin',
        'Audi',
        'Bentley',
        'BMW',
        'BMW Alpina',
        'Brilliance',
        'Bugatti',
        'Buick',
        'BYD',
        'Cadillac',
        'ChangFeng',
        'Chery',
        'Chevrolet',
        'Chrysler',
        'Citroen',
        'Dacia',
        'Dadi',
        'Daewoo',
        'Daihatsu',
        'Daimler',
        'De Tomaso',
        'Derways',
        'Dodge',
        'DongFeng',
        'Doninvest',
        'Eagle',
        'FAW',
        'Ferrari',
        'Fiat',
        'Ford',
        'Geely',
        'GMC',
        'Great Wall',
        'Hafei',
        'Haima',
        'Honda',
        'HuangHai',
        'Hummer',
        'Hurtan',
        'Hyundai',
        'Infiniti',
        'Iran Khodro',
        'Isuzu',
        'JAC',
        'Jaguar',
        'Jeep',
        'Kia',
        'Koenigsegg',
        'Lamborghini',
        'Lancia',
        'Land Rover',
        'Landwind',
        'Lexus',
        'Liebao Motor',
        'Lifan',
        'Lincoln',
        'Lotus',
        'Mahindra',
        'Maserati',
        'Maybach',
        'Mazda',
        'Mercedes-Benz',
        'Mercury',
        'Metrocab',
        'MG',
        'Mini',
        'Mitsubishi',
        'Mitsuoka',
        'Morgan',
        'Nissan',
        'Noble',
        'Oldsmobile',
        'Opel',
        'Peugeot',
        'Plymouth',
        'Pontiac',
        'Porsche',
        'Proton',
        'PUCH',
        'Renault',
        'Renault Samsung',
        'Rolls-Royce',
        'Rover',
        'Saab',
        'Saleen',
        'Saturn',
        'Scion',
        'SEAT',
        'ShuangHuan',
        'Skoda',
        'SMA',
        'Smart',
        'Spyker',
        'Ssang Yong',
        'Subaru',
        'Suzuki',
        'Talbot',
        'TATA',
        'Tatra',
        'Tazzari',
        'Tesla',
        'Tianma',
        'Tianye',
        'Toyota',
        'Trabant',
        'Triumph',
        'Volkswagen',
        'Volvo',
        'Vortex',
        'Wartburg',
        'Wiesmann',
        'Xin Kai',
        'Zastava',
        'ZX',
        'ВАЗ',
        'ГАЗ',
        'ЗАЗ',
        'ЗИЛ',
        'ИЖ',
        'КамАЗ',
        'ЛУАЗ',
        'Москвич (АЗЛК)',
        'СеАЗ',
        'СМЗ',
        'ТагАЗ',
        'УАЗ',
        'Эксклюзив'
    ],

    init: function(){
        $('#make').typeahead({
            source: this.makes
        });
    }
};

$(function(){
    core.fleet_add.init();
});